package kanban.manager;

import kanban.model.*;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

abstract class TaskManagerTest<T extends TaskManager> {
    protected T manager;

    protected HistoryManager historyManager;

    @Test
    void shouldCreateTaskWithAutoGeneratedIdWhenValidDataProvided() {
        manager.addTask("Task 1", "Description", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        Task createdTask = manager.getTask(1);
        assertNotNull(createdTask, "Задача должна существовать после создания");
        assertEquals("Task 1", createdTask.getTitle());
        assertEquals(TaskStatus.NEW, createdTask.getStatus());
    }

    @Test
    void shouldGenerateUniqueIdsWhenCreatingMultipleTasks() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addTask("Task 2", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        assertNotEquals(
                manager.getTask(1).getId(),
                manager.getTask(2).getId(),
                "ID задач должны быть уникальными"
        );
    }

    @Test
    void shouldReturnTaskByIdWhenTaskExists() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        Task task = manager.getTask(1);

        assertNotNull(task, "Должна возвращаться созданная задача");
        assertEquals(1, task.getId());
    }

    @Test
    void shouldReturnNullWhenGettingNonExistentTask() {
        assertNull(manager.getTask(999), "Должен возвращаться null для несуществующей задачи");
    }

    @Test
    void shouldAddTaskToHistoryWhenTaskWatched() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.getTask(1);

        List<Task> history = historyManager.getHistory();
        System.out.println(historyManager.getHistory());
        assertEquals(1, history.size(), "Задача должна добавляться в историю при получении");
        assertEquals(1, history.get(0).getId());
    }

    @Test
    void shouldUpdateTaskFieldsWhenTaskExists() {
        manager.addTask("Original", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        Task updated = new Task("Updated", "New Desc", 1, TaskStatus.DONE, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        manager.updateTask(updated);
        Task result = manager.getTask(1);

        assertEquals("Updated", result.getTitle());
        assertEquals("New Desc", result.getDescription());
        assertEquals(TaskStatus.DONE, result.getStatus());
    }

    @Test
    void shouldRemoveTaskWhenTaskExists() {
        manager.addTask("To remove", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.removeTask(1);

        assertNull(manager.getTask(1), "Задача должна удаляться");
        assertTrue(manager.getAllTasks().isEmpty());
    }

    @Test
    void shouldReturnAllTasksWhenTasksExist() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addTask("Task 2", "Desc", TaskStatus.IN_PROGRESS, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        List<Task> allTasks = manager.getAllTasks();
        assertEquals(2, allTasks.size());
        assertTrue(allTasks.stream().anyMatch(t -> t.getId() == 1));
        assertTrue(allTasks.stream().anyMatch(t -> t.getId() == 2));
    }

    @Test
    void shouldReturnEmptyListWhenNoTasksExist() {
        assertTrue(manager.getAllTasks().isEmpty(),
                "Должен возвращаться пустой список при отсутствии задач");
    }

    @Test
    void shouldRemoveAllTasksWhenClearTasksCalled() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addTask("Task 2", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        manager.deleteAllTasks();

        assertTrue(manager.getAllTasks().isEmpty());
        assertNull(manager.getTask(1));
        assertNull(manager.getTask(2));
    }

    @Test
    void shouldCreateEpicWithNewStatusWhenNoSubtasks() {
        manager.addEpic("Epic 1", "Description");
        Epic epic = manager.getEpic(1);

        assertNotNull(epic, "Эпик должен существовать после создания");
        assertEquals("Epic 1", epic.getTitle());
        assertEquals(TaskStatus.NEW, epic.getStatus());
        assertTrue(epic.getSubtaskIds().isEmpty(), "Список подзадач должен быть пустым");
    }

    @Test
    void shouldGenerateUniqueIdWhenCreatingEpic() {
        manager.addEpic("Epic 1", "Desc");
        manager.addEpic("Epic 2", "Desc");

        assertNotEquals(
                manager.getEpic(1).getId(),
                manager.getEpic(2).getId(),
                "ID эпиков должны быть уникальными"
        );
    }

    @Test
    void shouldReturnEpicByIdWhenEpicExists() {
        manager.addEpic("Epic", "Desc");
        Epic epic = manager.getEpic(1);

        assertNotNull(epic);
        assertEquals(1, epic.getId());
    }

    @Test
    void shouldAddEpicToHistoryWhenEpicWatched() {
        manager.addEpic("Epic", "Desc");
        manager.getEpic(1);

        List<Task> history = historyManager.getHistory();
        assertEquals(1, history.size());
        assertEquals(1, history.get(0).getId());
    }

    @Test
    void shouldRemoveEpicWhenEpicExists() {
        manager.addEpic("To remove", "Desc");
        manager.removeEpic(1);

        assertNull(manager.getEpic(1));
    }

    @Test
    void shouldRemoveSubtasksWhenEpicDeleted() {
        manager.addEpic("Epic", "Desc");
        manager.addSubtask("Sub 1", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addSubtask("Sub 2", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        manager.removeEpic(1);

        assertNull(manager.getSubtask(2));
        assertNull(manager.getSubtask(3));
    }

    @Test
    void shouldSetEpicStatusToNewWhenNoSubtasks() {
        manager.addEpic("Epic", "Desc");
        assertEquals(TaskStatus.NEW, manager.getEpic(1).getStatus());
    }

    @Test
    void shouldSetEpicStatusToDoneWhenAllSubtasksDone() {
        manager.addEpic("Epic", "Desc");
        manager.addSubtask("Sub", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.updateSubtask(new Subtask("Sub", "Desc", 2, TaskStatus.DONE, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0)));

        assertEquals(TaskStatus.DONE, manager.getEpic(1).getStatus());
    }

    @Test
    void shouldSetEpicStatusToInProgressWhenSubtasksMixed() {
        manager.addEpic("Epic", "Desc");
        manager.addSubtask("Sub 1", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addSubtask("Sub 2", "Desc", TaskStatus.DONE, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        assertEquals(TaskStatus.IN_PROGRESS, manager.getEpic(1).getStatus());
    }

    @Test
    void shouldUpdateEpicStatusWhenSubtaskStatusChanged() {
        manager.addEpic("Epic", "Desc");
        manager.addSubtask("Sub", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.updateSubtask(new Subtask("Sub", "Desc", 2, TaskStatus.IN_PROGRESS, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0)));

        assertEquals(TaskStatus.IN_PROGRESS, manager.getEpic(1).getStatus());
    }

    @Test
    void shouldReturnAllEpicsWhenEpicsExist() {
        manager.addEpic("Epic 1", "Desc");
        manager.addEpic("Epic 2", "Desc");

        List<Epic> epics = manager.getAllEpics();
        assertEquals(2, epics.size());
        assertTrue(epics.stream().anyMatch(e -> e.getId() == 1));
        assertTrue(epics.stream().anyMatch(e -> e.getId() == 2));
    }

    @Test
    void shouldReturnEmptyListWhenNoEpicsExist() {
        assertTrue(manager.getAllEpics().isEmpty());
    }

    @Test
    void shouldRemoveAllEpicsAndSubtasksWhenClearEpicsCalled() {
        manager.addEpic("Epic 1", "Desc");
        manager.addSubtask("Sub 1", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addEpic("Epic 2", "Desc");

        manager.deleteAllEpics();

        assertTrue(manager.getAllEpics().isEmpty());
        assertTrue(manager.getAllSubtasks().isEmpty());
    }

    @Test
    void shouldCreateSubtaskWithCorrectEpicLink() {
        manager.addEpic("Test Epic", "Description");
        manager.addSubtask("Subtask", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        Subtask subtask = manager.getSubtask(2);

        assertEquals(1, subtask.getEpicId(), "Подзадача должна быть привязана к эпику");
        assertTrue(manager.getEpic(1).getSubtaskIds().contains(subtask.getId()),
                "Эпик должен содержать подзадачу");
    }

    @Test
    void shouldUpdateSubtaskAndMaintainEpicLink() {
        manager.addEpic("Test Epic", "Description");
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        Subtask updated = new Subtask("Updated", "New Desc", 2, TaskStatus.DONE, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));

        manager.updateSubtask(updated);
        Subtask result = manager.getSubtask(2);

        assertEquals("Updated", result.getTitle());
        assertEquals(TaskStatus.DONE, result.getStatus());
        assertEquals(1, result.getEpicId());
    }

    @Test
    void shouldRemoveSubtaskFromEpicWhenDeleted() {
        manager.addEpic("Test Epic", "Description");
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addSubtask("To remove", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.removeSubtask(2);

        assertNull(manager.getSubtask(2));
        assertNotEquals(2, manager.getEpic(1).getSubtaskIds().get(0));
    }

    @Test
    void shouldReturnCorrectPrioritizedTasks() {
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 3, 1, 0, 0, 0, 0));
        manager.addSubtask("To remove", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addSubtask("To remove", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 2, 1, 0, 0, 0, 0));

        ArrayList<Integer> ids = new ArrayList<>();
        ids.add(2);
        ids.add(3);
        ids.add(1);

        assertEquals(manager.getPrioritizedTasks().stream().map(Task::getId).collect(Collectors.toList()), ids);
        assertEquals(manager.getPrioritizedTasks().size(), 3);
    }

    @Test
    void shouldReturnCorrectUpdatePrioritizedTasks() {
        manager.addEpic("Test Epic", "Description");
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 3, 1, 0, 0, 0, 0));

        Subtask updated = new Subtask("Updated", "New Desc", 2, TaskStatus.DONE, 1, Duration.ofMinutes(0), LocalDateTime.of(2001, 1, 1, 0, 0, 0, 0));
        manager.updateSubtask(updated);

        assertEquals(manager.getPrioritizedTasks().first().getStartTime().getYear(), 2001);
    }

    @Test
    void shouldReturnCorrectRemoveTaskFromPrioritizedTasks() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 3, 1, 0, 0, 0, 0));

        manager.removeTask(1);

        assertEquals(manager.getPrioritizedTasks().first().getId(), 2);
    }

    @Test
    void shouldReturnCorrectRemoveSubTaskFromPrioritizedTasks() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 3, 1, 0, 0, 0, 0));

        manager.removeSubtask(2);

        assertEquals(manager.getPrioritizedTasks().first().getId(), 1);
    }

    @Test
    void shouldReturnCorrectRemoveAllTasksFromPrioritizedTasks() {
        manager.addTask("Task 1", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addTask("Task 2", "Desc", TaskStatus.NEW, Duration.ofMinutes(0), LocalDateTime.of(2000, 1, 1, 0, 0, 0, 0));
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofMinutes(0), LocalDateTime.of(2000, 3, 1, 0, 0, 0, 0));

        manager.deleteAllTasks();

        assertEquals(manager.getPrioritizedTasks().first().getId(), 3);
    }

    @Test
    void checkTimeTaskAvailableShouldReturnTrueWhenNoTasks() {
        LocalDateTime baseTime = LocalDateTime.of(2025, 12, 25, 10, 0);

        boolean result = manager.checkTimeTaskAvailable(baseTime, Duration.ofMinutes(90));
        assertTrue(result, "Не должно быть конфликтов при пустом списке");
    }

    @Test
    void checkTimeTaskAvailableShouldReturnFalseWhenTimeOverlaps() {
        LocalDateTime baseTime = LocalDateTime.of(2025, 12, 25, 10, 0);

        manager.addTask("Task 1", "Description", TaskStatus.NEW, Duration.ofHours(2), baseTime);

        boolean result = manager.checkTimeTaskAvailable(
                baseTime.plusHours(1),
                Duration.ofMinutes(90)
        );

        assertFalse(result);
    }

    @Test
    void checkTimeTaskAvailableShouldReturnTrueWhenTimeDoesNotOverlap() {
        LocalDateTime baseTime = LocalDateTime.of(2025, 12, 25, 10, 0);

        manager.addTask("Task 1", "Description", TaskStatus.NEW, Duration.ofHours(2), baseTime);

        boolean result = manager.checkTimeTaskAvailable(
                baseTime.plusHours(3),
                Duration.ofHours(1)
        );

        assertTrue(result);
    }

    @Test
    void getEndTimeShouldUpdateWhenSubtasksAreModified() {
        LocalDateTime baseTime = LocalDateTime.of(2023, 12, 25, 10, 0);
        manager.addEpic("Test Epic", "Description");
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofHours(1), baseTime.plusHours(1));

        Epic epic = manager.getEpic(1);
        LocalDateTime initialEndTime = epic.getEndTime();

        manager.addSubtask("To remove", "Desc", TaskStatus.NEW, 1, Duration.ofHours(3), baseTime.plusHours(2));
        LocalDateTime updatedEndTime = epic.getEndTime();

        assertNotEquals(initialEndTime, updatedEndTime);
        assertTrue(updatedEndTime.isAfter(initialEndTime));
    }

    @Test
    void getEndTimeShouldReturnSubtaskEndTimeWhenSingleSubtask() {
        LocalDateTime baseTime = LocalDateTime.of(2023, 12, 25, 10, 0);
        manager.addEpic("Test Epic", "Description");
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofHours(1), baseTime.plusHours(1));
        Epic epic = manager.getEpic(1);

        LocalDateTime expectedEndTime = baseTime.plusHours(1).plusHours(1);
        assertEquals(expectedEndTime, epic.getEndTime());
    }

    @Test
    void getEndTimeShouldReturnLatestEndTimeWhenMultipleSubtasks() {
        LocalDateTime baseTime = LocalDateTime.of(2023, 12, 25, 10, 0);
        manager.addEpic("Test Epic", "Description");
        manager.addSubtask("Original", "Desc", TaskStatus.NEW, 1, Duration.ofHours(1), baseTime.plusHours(1));
        manager.addSubtask("To remove", "Desc", TaskStatus.NEW, 1, Duration.ofHours(3), baseTime.plusHours(2));

        Epic epic = manager.getEpic(1);

        LocalDateTime expectedEndTime = baseTime.plusHours(2).plusHours(3);
        assertEquals(expectedEndTime, epic.getEndTime());
    }
}
